// Local-privilege auth token resolution for the router/viewer pages.
//
// Where the token comes from, by host:
//   · Electron router window — the preload exposes window.rhAuth (per-install
//     token generated by the app's main process).
//   · OBS Browser Source (/viewer) — the app provisions the source URL with
//     ?auth=<token>; we lift it from the query string.
//   · CLI demo rig — no token configured server-side; everything passes.
// The token is cached in sessionStorage so SPA navigation (which drops query
// params) keeps it for the page's lifetime. The API client (lib/apiClient.ts)
// turns it into the x-rh-auth header; the hub socket sends it in `hello`.

const KEY = "rhAuthToken";

/** The privilege token for this page, if any. */
export function authToken(): string | undefined {
  const w = window as { rhAuth?: string };
  if (typeof w.rhAuth === "string" && w.rhAuth) return w.rhAuth;
  try {
    const fromQuery = new URLSearchParams(location.search).get("auth");
    if (fromQuery) {
      sessionStorage.setItem(KEY, fromQuery);
      return fromQuery;
    }
    return sessionStorage.getItem(KEY) ?? undefined;
  } catch {
    return undefined;
  }
}
