// Local-privilege auth token resolution for the router/viewer pages.
//
// Where the token comes from, by host:
//   · Electron router window — the preload exposes window.rhAuth (per-install
//     token generated by the app's main process).
//   · OBS Browser Source (/viewer) — the app provisions the source URL with
//     ?auth=<token>; we lift it from the query string.
//   · CLI demo rig — no token configured server-side; everything passes.
// The token is cached in sessionStorage so SPA navigation (which drops query
// params) keeps it for the page's lifetime.

const KEY = "rhAuthToken";

function resolve(): string | undefined {
  const w = window as { rhAuth?: string };
  if (typeof w.rhAuth === "string" && w.rhAuth) return w.rhAuth;
  try {
    const fromQuery = new URLSearchParams(location.search).get("auth");
    if (fromQuery) {
      sessionStorage.setItem(KEY, fromQuery);
      return fromQuery;
    }
    return sessionStorage.getItem(KEY) ?? undefined;
  } catch {
    return undefined;
  }
}

/** The privilege token for this page, if any. */
export function authToken(): string | undefined {
  return resolve();
}

/** fetch() headers carrying the token (empty when none). */
export function authHeaders(): Record<string, string> {
  const t = resolve();
  return t ? { "x-rh-auth": t } : {};
}
